#!/usr/bin/perl
sub put {
    foreach $one (@first) {
        foreach $two (@second) {
            print "$result = $one + $two\n";
        }
    }
    @first = ();
    @second = ();
    $plus = undef;
    $component = undef;
}
while (<>) {
    chomp;
    @words = split;
    if ($#words gt 1 && $words[1] eq "=") {
        put;
    }
    foreach (@words) {
        if (/\+/) {
            $plus = 1;
        } elsif (/=/) {
            $component = 1;
        } elsif ($plus) {
            push @second, $_;
        } elsif ($component) {
            push @first, $_;
        } else {
            $result = $_;
        }
    }
}
put;
